# Generated by Django 4.0.2 on 2022-03-12 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='free_sessionform',
            new_name='Freesession',
        ),
    ]
