# Generated by Django 4.0.2 on 2022-03-12 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_free_sessionform_freesession'),
    ]

    operations = [
        migrations.AddField(
            model_name='internship',
            name='checkbox1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='internship',
            name='checkbox2',
            field=models.BooleanField(default=False),
        ),
    ]
