# Generated by Django 4.0.2 on 2022-03-12 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_internship_checkbox1_internship_checkbox2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internship',
            name='checkbox1',
            field=models.BinaryField(default=False),
        ),
        migrations.AlterField(
            model_name='internship',
            name='checkbox2',
            field=models.BinaryField(default=False),
        ),
    ]
