# Generated by Django 4.0.2 on 2022-03-12 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_internship_checkbox1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internship',
            name='checkbox1',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='internship',
            name='checkbox2',
            field=models.BooleanField(default=False),
        ),
    ]
