# Generated by Django 4.0.2 on 2022-03-12 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='course_info',
            new_name='Course',
        ),
        migrations.RenameModel(
            old_name='Forum_table',
            new_name='Forum',
        ),
        migrations.RenameModel(
            old_name='hiring_mentor',
            new_name='Hirementor',
        ),
    ]
