from django.urls import path
from . import views
urlpatterns = [
    path('discussion',views.discussion),
    path('reply/<int:id>/',views.reply),
    path('redirect',views.redirect),
    path('session',views.session),
    path('prime',views.prime),
    path('step2',views.plan),
    path('step3',views.plan_next),
    path('nextpay',views.nextpay),
    path('paytm',views.paytm),
    path('callback',views.callback),
    path('directpay',views.directpay),
    path('qr',views.direct),
    path('netbanking',views.netbanking),
    path('paymentstart', views.testing),
    path('confirm_order', views.create_order),
    path('payment_status', views.payment_status,name = 'payment_status'),
    path('volunter',views.volunter),
    path('mentor',views.volunter_next),
    path('course',views.course),
    path('skilldevelopment',views.skill),
    path('softwaretrain',views.software),
    path('paydirect',views.paydirect),
    path('startnow',views.fillup),
    path('qrp',views.qrp),
    path('virtualcourt',views.virtualcourt),
    path('bookcourt',views.bookcourt),
    path('lastcall',views.booklast),
    path('calling',views.lastonly),
    path('itsolution',views.itsolution),
    path('digital',views.booksession),
    ]